CREATE TABLE cover(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL,
    content BLOB NOT NULL
);

CREATE TABLE owner(
    id INTEGER NOT NULL PRIMARY KEY,
    username TEXT NOT NULL
);

CREATE TABLE author(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    first_name TEXT,
    last_name TEXT NOT NULL
);

CREATE TABLE book(
    id INTEGER NOT NULL PRIMARY KEY,
    title TEXT NOT NULL,
    pub_year INTEGER,
    cover_id INTEGER REFERENCES cover(id) ON UPDATE CASCADE ON DELETE SET NULL,
    owner_id INTEGER NOT NULL REFERENCES owner(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE book_has_author(
    id INTEGER NOT NULL PRIMARY KEY,
    book_id INTEGER NOT NULL REFERENCES book(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    author_id INTEGER NOT NULL REFERENCES author(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
