# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import book_service_msg_pb2 as book__service__msg__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in book_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBooks = channel.unary_stream(
                '/BookService/GetBooks',
                request_serializer=book__service__msg__pb2.GetBooksRequest.SerializeToString,
                response_deserializer=book__service__msg__pb2.GetBooksResponse.FromString,
                _registered_method=True)
        self.GetBookById = channel.unary_unary(
                '/BookService/GetBookById',
                request_serializer=book__service__msg__pb2.GetBookByIdRequest.SerializeToString,
                response_deserializer=book__service__msg__pb2.GetBookByIdResponse.FromString,
                _registered_method=True)
        self.GetBooksByOwner = channel.unary_stream(
                '/BookService/GetBooksByOwner',
                request_serializer=book__service__msg__pb2.GetBooksByOwnerRequest.SerializeToString,
                response_deserializer=book__service__msg__pb2.GetBooksByOwnerResponse.FromString,
                _registered_method=True)
        self.AddBook = channel.unary_unary(
                '/BookService/AddBook',
                request_serializer=book__service__msg__pb2.AddBookRequest.SerializeToString,
                response_deserializer=book__service__msg__pb2.AddBookResponse.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/BookService/UpdateBook',
                request_serializer=book__service__msg__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=book__service__msg__pb2.UpdateBookResponse.FromString,
                _registered_method=True)
        self.RemoveBookCover = channel.unary_unary(
                '/BookService/RemoveBookCover',
                request_serializer=book__service__msg__pb2.RemoveBookCoverRequest.SerializeToString,
                response_deserializer=book__service__msg__pb2.RemoveBookCoverResponse.FromString,
                _registered_method=True)
        self.RemoveBook = channel.unary_unary(
                '/BookService/RemoveBook',
                request_serializer=book__service__msg__pb2.RemoveBookRequest.SerializeToString,
                response_deserializer=book__service__msg__pb2.RemoveBookResponse.FromString,
                _registered_method=True)


class BookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooksByOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBookCover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBooks': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBooks,
                    request_deserializer=book__service__msg__pb2.GetBooksRequest.FromString,
                    response_serializer=book__service__msg__pb2.GetBooksResponse.SerializeToString,
            ),
            'GetBookById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookById,
                    request_deserializer=book__service__msg__pb2.GetBookByIdRequest.FromString,
                    response_serializer=book__service__msg__pb2.GetBookByIdResponse.SerializeToString,
            ),
            'GetBooksByOwner': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBooksByOwner,
                    request_deserializer=book__service__msg__pb2.GetBooksByOwnerRequest.FromString,
                    response_serializer=book__service__msg__pb2.GetBooksByOwnerResponse.SerializeToString,
            ),
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=book__service__msg__pb2.AddBookRequest.FromString,
                    response_serializer=book__service__msg__pb2.AddBookResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=book__service__msg__pb2.UpdateBookRequest.FromString,
                    response_serializer=book__service__msg__pb2.UpdateBookResponse.SerializeToString,
            ),
            'RemoveBookCover': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBookCover,
                    request_deserializer=book__service__msg__pb2.RemoveBookCoverRequest.FromString,
                    response_serializer=book__service__msg__pb2.RemoveBookCoverResponse.SerializeToString,
            ),
            'RemoveBook': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBook,
                    request_deserializer=book__service__msg__pb2.RemoveBookRequest.FromString,
                    response_serializer=book__service__msg__pb2.RemoveBookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('BookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/BookService/GetBooks',
            book__service__msg__pb2.GetBooksRequest.SerializeToString,
            book__service__msg__pb2.GetBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BookService/GetBookById',
            book__service__msg__pb2.GetBookByIdRequest.SerializeToString,
            book__service__msg__pb2.GetBookByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBooksByOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/BookService/GetBooksByOwner',
            book__service__msg__pb2.GetBooksByOwnerRequest.SerializeToString,
            book__service__msg__pb2.GetBooksByOwnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BookService/AddBook',
            book__service__msg__pb2.AddBookRequest.SerializeToString,
            book__service__msg__pb2.AddBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BookService/UpdateBook',
            book__service__msg__pb2.UpdateBookRequest.SerializeToString,
            book__service__msg__pb2.UpdateBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveBookCover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BookService/RemoveBookCover',
            book__service__msg__pb2.RemoveBookCoverRequest.SerializeToString,
            book__service__msg__pb2.RemoveBookCoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BookService/RemoveBook',
            book__service__msg__pb2.RemoveBookRequest.SerializeToString,
            book__service__msg__pb2.RemoveBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
