# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import book_service_msg_pb2 as book__service__msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62ook_service.proto\x1a\x16\x62ook_service_msg.proto2\xa4\x03\n\x0b\x42ookService\x12\x31\n\x08GetBooks\x12\x10.GetBooksRequest\x1a\x11.GetBooksResponse0\x01\x12\x38\n\x0bGetBookById\x12\x13.GetBookByIdRequest\x1a\x14.GetBookByIdResponse\x12\x46\n\x0fGetBooksByOwner\x12\x17.GetBooksByOwnerRequest\x1a\x18.GetBooksByOwnerResponse0\x01\x12,\n\x07\x41\x64\x64\x42ook\x12\x0f.AddBookRequest\x1a\x10.AddBookResponse\x12\x35\n\nUpdateBook\x12\x12.UpdateBookRequest\x1a\x13.UpdateBookResponse\x12\x44\n\x0fRemoveBookCover\x12\x17.RemoveBookCoverRequest\x1a\x18.RemoveBookCoverResponse\x12\x35\n\nRemoveBook\x12\x12.RemoveBookRequest\x1a\x13.RemoveBookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKSERVICE']._serialized_start=47
  _globals['_BOOKSERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
