CREATE TABLE IF NOT EXISTS person(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS song(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    pub_year INTEGER NOT NULL,
    artist_id INTEGER NOT NULL,
    album_id INTEGER NOT NULL,
    FOREIGN KEY (artist_id) REFERENCES person(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (album_id) REFERENCES album(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS album(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    artist_id INTEGER NOT NULL,
    FOREIGN KEY (artist_id) REFERENCES person(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS book(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    pub_year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS book_has_author(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    book_id INTEGER NOT NULL,
    author_id INTEGER NOT NULL,
    FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (author_id) REFERENCES person(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS movie(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    pub_year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tv_series(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    pub_year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS season(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    number INTEGER NOT NULL,
    pub_year INTEGER NOT NULL,
    series_id INTEGER NOT NULL,
    FOREIGN KEY (series_id) REFERENCES tv_series(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS episode(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    number INTEGER NOT NULL,
    pub_date TEXT NOT NULL,
    series_id INTEGER NOT NULL,
    season_id INTEGER,
    FOREIGN KEY (series_id) REFERENCES tv_series(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (season_id) REFERENCES season(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

