# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: toy_grpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'toy_grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etoy_grpc.proto\"!\n\x13GetMediaByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"D\n\rMediaResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x18\n\x04type\x18\x03 \x01(\x0e\x32\n.MediaType*\x8c\x01\n\tMediaType\x12\x16\n\x12MEDIA_TYPE_UNKNOWN\x10\x00\x12\x14\n\x10MEDIA_TYPE_MUSIC\x10\x01\x12\x13\n\x0fMEDIA_TYPE_BOOK\x10\x02\x12\x14\n\x10MEDIA_TYPE_MOVIE\x10\x03\x12\x11\n\rMEDIA_TYPE_TV\x10\x04\x12\x13\n\x0fMEDIA_TYPE_GAME\x10\x05\x32\x44\n\x0cMediaService\x12\x34\n\x0cGetMediaById\x12\x14.GetMediaByIdRequest\x1a\x0e.MediaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'toy_grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEDIATYPE']._serialized_start=124
  _globals['_MEDIATYPE']._serialized_end=264
  _globals['_GETMEDIABYIDREQUEST']._serialized_start=18
  _globals['_GETMEDIABYIDREQUEST']._serialized_end=51
  _globals['_MEDIARESPONSE']._serialized_start=53
  _globals['_MEDIARESPONSE']._serialized_end=121
  _globals['_MEDIASERVICE']._serialized_start=266
  _globals['_MEDIASERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
